### ISSUE TITLE
Opcode Numbers Don’t Look Right

### ISSUE THREAD

**Issue by ldo** [ideasman42/py_safe_math_eval#1]
The numbers you use for opcodes don’t correspond to those in the [`dis`](https://docs.python.org/3/library/dis.html) module. For example, you have `NOP` at 0, whereas it should be 9. Here’s a very simple example I just tried:

```
>>> c = compile("pass", "--test--", "exec")
```

Here is the opcode dump:

```
>>> list(c.co_code)
[100, 0, 0, 83]
```

Symbolic disassembly:

```
>>> dis.dis(c)
  1           0 LOAD_CONST               0 (None)
              3 RETURN_VALUE
```

In your list, you have `LOAD_CONST` at index 33, and `RETURN_VALUE` at 32.

Summary: get the codes from `dis`.

**Comment by ideasman42** [comment]
@ldo, Thanks for looking into the script, but double checked and `NOP` is 9. `opcode_whitelist` is a set, the opcodes are looked up on the line:

`opcode_whitelist_index = {opname_reverse[name] for name in opcode_whitelist}`

**Comment by ldo** [comment]
Ah, sorry, I missed the import.
