### ISSUE TITLE
More concise construction of whitelist set

### ISSUE THREAD

**Issue by ldo** [ideasman42/py_safe_math_eval#2]
The set of whitelisted operators can be constructed with slightly less code:
[ldo-construct-whitelist.patch.txt](https://github.com/ideasman42/py_safe_math_eval/files/198545/ldo-construct-whitelist.patch.txt)

**Comment by ideasman42** [comment]
Ah, wasn't aware you update sets from dicts.
Committed baae9f0bdc9ac80cc1f681e35d2f06c47628ae82

**Comment by ldo** [comment]
Neither was I until I tried it. :)
