### ISSUE TITLE
Report all names not in whitelist

### ISSUE THREAD

**Issue by ldo** [ideasman42/py_safe_math_eval#3]
It might be nicer to report all names found that were not in the whitelist, rather than just the first one.

[ldo-report-all-non-whitelist.patch.txt](https://github.com/ideasman42/py_safe_math_eval/files/198558/ldo-report-all-non-whitelist.patch.txt)

**Comment by ideasman42** [comment]
Committed 7019b4c668d65686bfb0d211f8e2054735c4bc7b
